### ISSUE TITLE
0.1.2版本

### ISSUE THREAD

**Issue by Jacklintw** [Kiyoshimo/SuperCasino#1]
這個版本的buttonRaise內的showNormalDialog 是可以直接正常的叫用嗎?
我載下來試開都會閃退呢?

**Comment by Kiyoshimo** [comment]
当时的showNormalDialog 是会闪退没错，我现在修好了！

**Comment by Kiyoshimo** [comment]
请查看0.2.1的版本😂！

**Comment by Jacklintw** [comment]
哦哦 感謝~
